<template><h1 id="迭代器工具类" tabindex="-1"><a class="header-anchor" href="#迭代器工具类" aria-hidden="true">#</a> 迭代器工具类</h1>
<p><strong>Iterators</strong> 是 Guava 中对 Iterator 迭代器操作的帮助类，这个类提供了很多有用的方法来简化 Iterator 的操作。</p>
<blockquote>
<p>再次提醒，<strong>Iterator</strong> 是迭代器；<em>Iterable</em> 是接口，它是 <em>Collection</em> 的父接口。</p>
</blockquote>
<h2 id="all-方法-判断迭代器中的元素是否都满足某个条件" tabindex="-1"><a class="header-anchor" href="#all-方法-判断迭代器中的元素是否都满足某个条件" aria-hidden="true">#</a> all 方法：判断迭代器中的元素是否都满足某个条件</h2>
<p><strong>all</strong> 方法的第一个参数是 <em>Iterator</em>，第二个参数是 <code>Predicate&lt;String&gt; </code>的实现，这个方法的意义是不需要我们自己去写 <strong>while</strong> 循环了，他的内部实现中帮我们做了循环，把循环体中的条件判断抽象出来了。</p>
<p>伪代码：</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// false</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">all</span><span class="token punctuation">(</span>
    <span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token string">"Pear"</span><span class="token punctuation">,</span> <span class="token string">"Peach"</span><span class="token punctuation">,</span> <span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    input <span class="token operator">-></span> input<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"P"</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// true</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">all</span><span class="token punctuation">(</span>
    <span class="token punctuation">{</span><span class="token string">"Pear"</span><span class="token punctuation">,</span> <span class="token string">"Peach"</span><span class="token punctuation">,</span> <span class="token string">"Peter"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    input <span class="token operator">-></span> input<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"P"</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="any-方法-判断迭代器中是否至少有一个满足条件" tabindex="-1"><a class="header-anchor" href="#any-方法-判断迭代器中是否至少有一个满足条件" aria-hidden="true">#</a> any 方法：判断迭代器中是否至少有一个满足条件</h2>
<p><strong>any</strong> 方法的参数和 <strong>all</strong> 方法一样，就不再具体举例了。</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// true</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">any</span><span class="token punctuation">(</span>
    <span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token string">"Pear"</span><span class="token punctuation">,</span> <span class="token string">"Peach"</span><span class="token punctuation">,</span> <span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    input <span class="token operator">-></span> input<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"P"</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// true</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">any</span><span class="token punctuation">(</span>
    <span class="token punctuation">{</span><span class="token string">"Pear"</span><span class="token punctuation">,</span> <span class="token string">"Peach"</span><span class="token punctuation">,</span> <span class="token string">"Peter"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    input <span class="token operator">-></span> input<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"P"</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="get-方法-获得迭代器中的第-x-个元素" tabindex="-1"><a class="header-anchor" href="#get-方法-获得迭代器中的第-x-个元素" aria-hidden="true">#</a> get 方法：获得迭代器中的第 x 个元素</h2>
<p>第二个参数从 0 开始算起。</p>
<p>伪代码如下：</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// Apple</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span><span class="token string">"Pear"</span><span class="token punctuation">,</span><span class="token string">"Peach"</span><span class="token punctuation">,</span><span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Pear</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span><span class="token string">"Pear"</span><span class="token punctuation">,</span><span class="token string">"Peach"</span><span class="token punctuation">,</span><span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Peach</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span><span class="token string">"Pear"</span><span class="token punctuation">,</span><span class="token string">"Peach"</span><span class="token punctuation">,</span><span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="filter-方法-过滤、选中符合条件的项" tabindex="-1"><a class="header-anchor" href="#filter-方法-过滤、选中符合条件的项" aria-hidden="true">#</a> filter 方法：过滤、选中符合条件的项</h2>
<p>伪代码如下：</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// { Pear Peach }</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span>
    <span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token string">"Pear"</span><span class="token punctuation">,</span> <span class="token string">"Peach"</span><span class="token punctuation">,</span> <span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    item <span class="token operator">-></span> item<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"P"</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h2 id="find-方法-返回符合条件的第一个元素" tabindex="-1"><a class="header-anchor" href="#find-方法-返回符合条件的第一个元素" aria-hidden="true">#</a> find 方法：返回符合条件的第一个元素</h2>
<p>伪代码如下：</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// Pear</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">find</span><span class="token punctuation">(</span>
    <span class="token punctuation">{</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token string">"Pear"</span><span class="token punctuation">,</span> <span class="token string">"Peach"</span><span class="token punctuation">,</span> <span class="token string">"Banana"</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    item <span class="token operator">-></span> item<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"P"</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h2 id="transform-方法-对迭代器元素做转换" tabindex="-1"><a class="header-anchor" href="#transform-方法-对迭代器元素做转换" aria-hidden="true">#</a> transform 方法：对迭代器元素做转换</h2>
<p>伪代码如下：</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// { 5, 4, 5, 6 }</span>
<span class="token class-name">Iterators</span><span class="token punctuation">.</span><span class="token function">transform</span><span class="token punctuation">(</span>
    list<span class="token punctuation">.</span><span class="token function">iterator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
    item <span class="token operator">-></span> item<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>上面的例子中我们将字符串转换成了其长度，<strong>transform</strong> 方法输出的是另外一个 Iterator 。</p>
</template>
