name: Deploy VuePress

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 必须使用绝对路径或基于根目录的精确路径
          publish_dir: ./docs/.vuepress/dist
          # 确保不排除这些目录
          keep_files: false
          force_orphan: true
